---
jenkins_master_ip_address: 192.168.10.100
jenkins_master_full_name: jenkins_master-ubuntu-bionic-x86_64
jenkins_master_host_url: jenkins_master.ubuntu.local
docker_slave_ip_address: 192.168.10.101
docker_slave_full_name: docker_slave-ubuntu-bionic-x86_64
docker_slave_host_url: docker-slave.ubuntu.local
docker_slave_ami_id: ami-03bafa9277cc82cf8
windows_rust_slave_ip_address: 192.168.10.102
windows_rust_slave_full_name: rust_slave-windows-2016-x86_64
windows_rust_slave_host_url: rust_slave.ubuntu.local
windows_rust_slave_working_path: "c:\\jenkins-work"
jenkins_admin_user: qa
secret_jenkins_admin_user_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  62343932623532633537653833303661643466396661353134353230633738303535323133616535
  6331656463636634376133656262336334663165363361610a336535623436333163663032356438
  32306165303665393539386437633665323532343033363632616366393533393164316538633962
  3565643362343234370a346662383561383938316464616661663235633766383864353563613961
  38626264653832666538666335616334623462373131396534346264336534316235353666393437
  3863643464643932626265303062356131636533316265383433
rust_version: stable
osx_rust_slave_full_name: rust_slave-macos-mojave-x86_64
linux_slaves_security_group_name: linux_slaves-dev
slave_vpc_subnet_id: subnet-03f89f6a
jenkins_workspace_block_device: /dev/xvdb
jenkins_workspace_mount_point: /mnt/jenkins_workspace
docker_slave_ssh_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDkKreOrqHVOsvuHR2af52CfzwR/HShejDzuwz+qCq1g2FJWQfvOYlV6U31rJ9QzaSKdUhdLg4O2WQS5Y2D5z36fn/Nwd/bgG7dKl0/1Mb8AELrCa5E3NUl5bEiEEbw5O/KPk/eOygD8LqbkaBTSpC8WpAAdpU4ulElXpVbdCkTh0+YgMOFjrMts8qhFWJ94d3jatW4l2egJlPBVpftTs/4fYfJOaPMqDLFMg0hpiJ1gIItkPrbmAdjERR8Va5C7jpJ8PG+qiO4faWJqjj6hHY8nXSfs1CgGx/dkOF2Cp2E+YR+/xfsydyxc6Fz1gaPBK4JxU3UCbzeZMWNQNa1IrXJ
