---
letsencrypt_cert_path: "/etc/letsencrypt/live/{{ jenkins_url }}/"
cert_path: "/etc/ssl/{{ jenkins_url }}/full.pem"

# This is the production server. For development work, override this variable to work with
# the staging environment. The staging server is at https://acme-v01.api.letsencrypt.org/directory.
letsencrypt_server: https://acme-v01.api.letsencrypt.org/directory
