---
- name: 'load os specific variables'
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"

- fail:
    msg: "An IP address or hostname must be supplied for wg_server_endpoint. Run Ansible again and pass the server endpoint with -e."
  when: wg_server_endpoint is not defined or wg_server_endpoint == ""

- name: 'copy configuration'
  template:
    src: wg0.conf
    dest: "{{ wg_config_path }}/wg0.conf"
    mode: 0644
    owner: "{{ root_user }}"
    group: "{{ root_group }}"

- name: 'start the wireguard service'
  service:
    name: wg-quick@wg0
    state: started
    enabled: yes
  when: ansible_distribution != 'MacOSX'

- name: 'stop wireguard (if not running this task will error but that is fine) (macOS)'
  command: wg-quick down wg0
  ignore_errors: yes
  when: ansible_distribution == 'MacOSX'

- name: 'start wireguard (macOS)'
  command: wg-quick up wg0
  when: ansible_distribution == 'MacOSX'
